nodeLinker: node-modules

yarnPath: ".yarn/releases/yarn-berry.cjs"

npmScopes:
  "remix-run":
    npmRegistryServer: "https://npm.remix.run"
    npmAuthToken: "${REMIX_AUTH_TOKEN}"
    npmAlwaysAuth: true
